version: '3.8'

services:
  rpssl.api:
    container_name: rpssl-api
    build:
      context: .
      dockerfile: RPSSL.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - CODECHALLENGEAPI__BASEADDRESS=${CODECHALLENGEAPI__BASEADDRESS}

  rpssl.frontend:
    container_name: rpssl-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - rpssl.api
    environment:
      - VITE_RPSSL_API_BASE_URL=http://rpssl.api:8080
