name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CODECHALLENGEAPI__BASEADDRESS: ${{ vars.CODE_CHALLENGE_API_BASE_ADDRESS }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Ensure Docker is installed on the server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HETZNER_HOST }}
        username: ${{ secrets.HETZNER_USERNAME }}
        key: ${{ secrets.HETZNER_SSH_KEY }}
        script: |
          if ! command -v docker &> /dev/null; then
              echo "Docker could not be found, installing now..."
              sudo apt-get update
              sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
              sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
              sudo apt-get update
              sudo apt-get install -y docker-ce
              echo "Docker installed successfully."
          else
              echo "Docker is already installed."
          fi

          if ! command -v docker-compose &> /dev/null; then
              echo "Docker Compose could not be found, installing now..."
              sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
              echo "Docker Compose installed successfully."
          else
              echo "Docker Compose is already installed."
          fi

    - name: Clear Project Directory and Clone Repository
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HETZNER_HOST }}
        username: ${{ secrets.HETZNER_USERNAME }}
        key: ${{ secrets.HETZNER_SSH_KEY }}
        script: |
          if [ -d "/home/abeker/rpssl" ]; then
            echo "Clearing existing project directory..."
            rm -rf /home/abeker/rpssl
          fi
          echo "Cloning the repository..."
          git clone https://github.com/abeker/RPSSL.git /home/abeker/rpssl

    - name: Pull Latest Code and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HETZNER_HOST }}
        username: ${{ secrets.HETZNER_USERNAME }}
        key: ${{ secrets.HETZNER_SSH_KEY }}
        script: |
          cd /home/abeker/rpssl
          export CODECHALLENGEAPI__BASEADDRESS=${{ vars.CODE_CHALLENGE_API_BASE_ADDRESS }}
          docker-compose down --volumes --remove-orphans
          docker-compose pull
          docker-compose up -d
